### PR TITLE
Vars to configuration

### LINKED ISSUE #2: Variables are overwritten with update
Updating with HACS will overwrite the variables in sensor.py. These should be moved to configuration.yaml.

I will work on this coming days. 

@Magalex2x14 can you let me know what can be taken as constants and what you want in configuration.yaml? I think the limits do not have to be in configuration.yaml, am I right?

### PR DESCRIPTION
**Pull request by Ernst79**
- Moved the variables to configuration.yaml to keep them when upgrading the component (fixes #2 )
- Moved the constants to const.py
- Updated README.md and info.md

### CODE REVIEW

**Comment by Ernst79** [comment]
@Magalex2x14 Can you check if all variables work. I was able to see that decimals and period work fine, the others I'm not sure how to check if they work. 

Example of the configuration

```
sensor:
  - platform: mitemp_bt
    rounding: True
    decimals: 3
    period: 60
    log_spikes: False
    use_median: True
    hcitool_active: False
```

**Comment by Magalex2x14** [comment]
Yes, today a little later I will have the opportunity to check. I’ll write how I’ll finish. At the same time I can add a commit with readme update.

**Comment by Ernst79** [comment]
I added the description that you had in the python code in the README,md and info.md. You can just modify it.

**Comment by Magalex2x14** [comment]
@Ernst79 I checked the parameters work, everything is fine. Please look at my changes in the readme and info.md, and correct my English, if it's necessary )

**Comment by Magalex2x14** [comment]
@Ernst79 Please look at my changes in the readme and info.md, and feel free to correct my English, if it's necessary )

**Comment by Magalex2x14** [comment]
Thank you

**Comment by Ernst79** [comment]
Glad I could help

**Pull request merged**
