### PR TITLE
BLE ADV decryption

### PR DESCRIPTION
**Pull request by Magalex2x14**
Almost all weekend spent for intensive testing. Found several bugs (including those not related to decryption). I think the branch is ready for the master.
Changes:

- encrypted BLE ADV payload decryption implemented
- added new option `encryptors` to describe the correspondence between the mac-address of the sensor broadcasting encrypted adverts and the encryption key
- LYWSD03MMC support ("encryptor")
- added new option `report_unknown` designed to enable logging of all BLE ADV messages from unsupported Xiaomi ecosystem devices (greatly simplify life when implementing support for new sensors and eliminates hcidump and root shell dependency)
- error "Attribute hass is None for Entity..." fixed
- other minor bugfixes and improvements

README and FAQ also updated

### CODE REVIEW

**Comment by Ernst79** [comment]
Wow, you worked hard on this, well done! I will check it today. I have followed the discussions about the development of support for the LYWSD03MMC sensor last week. Unfortunately, I don’t have a LYWSD03MMC myself to check if this works in real life. So perhaps you can also ask someone in the LYWSD03MMC issue to test it as well. I will check the readme and faq. I will also look through the code, but keep in mind I’m not a programmer, I just learned a little python by DIY.

**Comment by Ernst79** [comment]
The instructions on how to get the key are referring to several topics in the LYWSD03MMC issue topic now. I think it would be better to give complete instructions in the faq (or a new, separate page). I haven’t installed these tools, but for a less skilled user, it should be clear what to do, where to look for the key, etc. I’m afraid you will now get a lot of issues of people who can’t find the key. Or are these tools clear for everybody?

**Comment by Ernst79** [comment]
I've checked it. Some small code formatting fixes to fix pylint, flake8 and black formatting requirements. 

As said, running fine on my LYWSDCGQ, but haven't checked with the new LYWSD03MMC., as I don't have this sensor. 

I've changed the logger level from 'info' to 'debug' for the new report_unknown option.

_LOGGER.info is reserved for the core, use _LOGGER.debug for anything else, see https://developers.home-assistant.io/docs/development_guidelines#log-messages

**Comment by Magalex2x14** [comment]
> _LOGGER.info is reserved for the core, use _LOGGER.debug for anything else, see

Yes, I forget this every time...

>  I think it would be better to give complete instructions in the faq (or a new, separate page). I haven’t installed these tools, but for a less skilled user, it should be clear what to do, where to look for the key, etc. I’m afraid you will now get a lot of issues of people who can’t find the key. Or are these tools clear for everybody?

I think you're right, it will be necessary to write a detailed instruction on obtaining the key. I think that I am ready for issues, and the accumulated user experience will help in writing instructions.

I'm sure of the code, since in fact the parser is the same for all types of sensors, decryption simply puts the decrypted part back into the packet, as if it had not been encrypted. In addition, there are positive feedback in the LYWSD03 issue.

> but` keep in mind I’m not a programmer, I just learned a little python by DIY

Me too :) But the further I go, the more I have to dive into it. Interesting experience )

Thank you, Ernst, very much!

**Comment by Ernst79** [comment]
No problem, you’re welcome.

Instruction can always be added later, yes.

**Pull request merged**
