### PR TITLE
code cleaning

### PR DESCRIPTION
**Pull request by Ernst79**
Some cleaning of part of the code

### CODE REVIEW

**Comment by Ernst79** [comment]
@Magalex2x14 This was one of your own code optimizations you had in 0.7.1 beta. I just did it again on the latest code (all credits to you :-).

**Comment by Magalex2x14** [comment]
OK )

**Review by Magalex2x14 — APPROVED** [review]

**Comment by Magalex2x14** [comment]
There are many good changes in that branch, but there were also controversial ones. Since I broke that stream with my long absence, now I can't remember all the nuances. I remember one thing - there was a change that spawned the data collection thread only once at system startup. Now we have this thread re-created each time at the beginning of a new measurement period. I think it's better to leave it that way until we learn to catch all possible problems on the hci interface. Otherwise, users who use our component in conjunction with other bt components risk being left without data at all...

**Comment by Magalex2x14** [comment]
If you like, then keep pushing those changes to the current branch. I didn't plan to return to that beta anytime soon. I want to finish reading the missed issues first.

**Comment by Ernst79** [comment]
Yes, sure. I started with the easy changes :-). I propose to make small steps (commits). I also have an idea about the configuration parameters, but will make a separate issue for that to discuss.

**Pull request merged**
