### PR TITLE
No external tools

### PR DESCRIPTION
**Pull request by Magalex2x14**

### CODE REVIEW

**Comment by Ernst79** [comment]
I will check it tonight (European time)

**Comment by Magalex2x14** [comment]
Looks good, but I have a question. I always thought that parenthesis when unpacking tuples in python are optional (lines 140-159). You put them based on some kind of requirement (lint or something)?

**Comment by Ernst79** [comment]
The change was made by Black. I normally copy and paste my code on [black.now.sh](black.now.sh). This site applies black formatting which is required for official components in Home Assistant. You can just copy and paste your code and copy the altered code back to github. See also [black website](https://black.readthedocs.io/en/stable/). 

Pylint and flake8 didn't complain about your original code, so both ways are probably correct, as you say. The only problem when making the custom component an official HA integration in the future is that it has to be black compliant, (and also pylint compliant and flake8 compliant). So I thought it is better to do this right now, to safe you some work later.

**Comment by Magalex2x14** [comment]
OK! Thanks for this info!

**Pull request merged**
