### PR TITLE
Add Frequently Asked Questions

### PR DESCRIPTION
**Pull request by Ernst79**
@Magalex2x14 I have set up an initial version of the FAQ. Could you review it and merge it if it is OK. We can always add things later, but we have a start for now. I also updated a link to HACS, which changed its URL.

### CODE REVIEW

**Comment by Magalex2x14** [comment]
Thanks, I was just about to add something about conflicts

**Comment by Ernst79** [comment]
Sure, go ahead.

**Comment by Magalex2x14** [comment]
Please, review my additions and then merge.

**Comment by Magalex2x14** [comment]
Also merged into no-external-tools.

**Comment by Ernst79** [comment]
Great. I think the end of step 1 of the ‘How to install’ in no-external-tools can be removed. Just make a sentence like “If you get a PermissionError in Home Assistant, check the FAQ for a possible solution.”

**Pull request merged**
