### PR TITLE
case insensitive configuration

### PR DESCRIPTION
**Pull request by Ernst79**
Fix for #136 

- This PR makes the MAC address of the `sensor_names` and `sensor_fahrenheit` options case insensitive. 
- Small improvement in the debugging messages when using `sensor_names`

### CODE REVIEW

**Comment by Ernst79** [comment]
@Magalex2x14 Before releasing 0.7.7 another fix (see #136). Can you have a look at this PR as well?

**Comment by andras-tim** [comment]
Many thanks for this super-fast answer! :slightly_smiling_face:

**Review by Magalex2x14 — COMMENTED** [review]
Line 1039 (unique_id fo switch sensor) looks suspicious)

**Comment by Ernst79** [comment]
You’re right, will change that

**Comment by Ernst79** [comment]
Fixed

**Comment by Magalex2x14** [comment]
Until now, I have not used the sensor_names option.
Now I have registered a name for one of the sensors.
I don't see any more problems, everything works.

**Comment by Ernst79** [comment]
Thanks. sensor_names was a request by some users. It is actually quite convienient.

**Review by Magalex2x14 — APPROVED** [review]

**Pull request merged**
