### PR TITLE
Change a debug message to info

### PR DESCRIPTION
**Pull request by borpin**
It would be really useful to have the final message on the success of the scanning.

Even better would be a sensor with this info.

### CODE REVIEW

**Comment by Ernst79** [comment]
@Magalex2x14 

It looks OK to me, but can you confirm that this is only happening on the initial discovery of a new device (so it happens only once)?

**Comment by borpin** [comment]
No it will give you the message every cycle. It is useful to monitor how well the integration is running. At the moment running at `DEBUG` give a lot of info, I'd rather run at Info and just get one message i.e. the last one.

The reason I'm using it is, that the integration doesn't always find all the sensors.

I also sometime lose one of the hci interfaces. Something that tells me which interfaces were detected would be useful.

Perhaps an overall status sensor?

```
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] update_ble called
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] Discovering Bluetooth LE devices
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] Time to analyze...
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] Getting data from HCIdump thread
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: joining
2020-07-17 09:04:14 DEBUG (Thread-26366) [custom_components.mitemp_bt.sensor] HCIdump thread: main event_loop stopped, finishing
2020-07-17 09:04:14 DEBUG (Thread-26366) [custom_components.mitemp_bt.sensor] HCIdump thread: Run finished
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: joined
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: joining
2020-07-17 09:04:14 DEBUG (Thread-26367) [custom_components.mitemp_bt.sensor] HCIdump thread: main event_loop stopped, finishing
2020-07-17 09:04:14 DEBUG (Thread-26367) [custom_components.mitemp_bt.sensor] HCIdump thread: Run finished
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: joined
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: joining
2020-07-17 09:04:14 DEBUG (Thread-26368) [custom_components.mitemp_bt.sensor] HCIdump thread: main event_loop stopped, finishing
2020-07-17 09:04:14 DEBUG (Thread-26368) [custom_components.mitemp_bt.sensor] HCIdump thread: Run finished
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: joined
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] Spawning HCIdump thread(s).
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: Init
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: Init finished
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] Starting HCIdump thread for hci0
2020-07-17 09:04:14 DEBUG (Thread-26369) [custom_components.mitemp_bt.sensor] HCIdump thread: Run
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: Init
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: Init finished
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] Starting HCIdump thread for hci1
2020-07-17 09:04:14 DEBUG (Thread-26369) [custom_components.mitemp_bt.sensor] HCIdump thread: Connection
2020-07-17 09:04:14 DEBUG (Thread-26369) [custom_components.mitemp_bt.sensor] HCIdump thread: Connected
2020-07-17 09:04:14 DEBUG (Thread-26369) [custom_components.mitemp_bt.sensor] HCIdump thread: start main event_loop
2020-07-17 09:04:14 DEBUG (Thread-26370) [custom_components.mitemp_bt.sensor] HCIdump thread: Run
2020-07-17 09:04:14 DEBUG (Thread-26370) [custom_components.mitemp_bt.sensor] HCIdump thread: Connection
2020-07-17 09:04:14 DEBUG (Thread-26370) [custom_components.mitemp_bt.sensor] HCIdump thread: Connected
2020-07-17 09:04:14 DEBUG (Thread-26370) [custom_components.mitemp_bt.sensor] HCIdump thread: start main event_loop
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: Init
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump thread: Init finished
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] Starting HCIdump thread for hci2
2020-07-17 09:04:14 DEBUG (Thread-26371) [custom_components.mitemp_bt.sensor] HCIdump thread: Run
2020-07-17 09:04:14 DEBUG (Thread-26371) [custom_components.mitemp_bt.sensor] HCIdump thread: Connection
2020-07-17 09:04:14 DEBUG (Thread-26371) [custom_components.mitemp_bt.sensor] HCIdump thread: Connected
2020-07-17 09:04:14 DEBUG (Thread-26371) [custom_components.mitemp_bt.sensor] HCIdump thread: start main event_loop
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] HCIdump threads count = 3
2020-07-17 09:04:14 DEBUG (SyncWorker_1) [custom_components.mitemp_bt.sensor] Finished. Parsed: 2063 hci events, 5 xiaomi devices.
```

**Comment by Ernst79** [comment]
Hmm, I’m not sure then. You don’t want messages in your log if everything is running fine, to my opinion. In your case you need it, because it doesn’t run fine. That is where debug level is for. But I understand your issue, that debug level can give a lot of log messages. I’ll have to discuss with @Magalex2x14, but he is busy at the moment. A status sensor might be an idea.

**Comment by borpin** [comment]
I always feel that 'info' tells me what is happening (e.g. x events parsed).  `debug` gives more information how it got there. If you don't want anything in the logs except problems, you just log `warn`.

Log levels are tricky and it is very much like Marmite.

**Comment by Ernst79** [comment]
Yes, what you say makes sense. But I now remember why we didn’t use the info level. The developer documentation of home assistant states the following. 

_Also_ note that _LOGGER.info is reserved for the core, use _LOGGER.debug for anything else.__

**Comment by borpin** [comment]
Typical of the devs IMHO.

**Pull request closed without merging**
