### PR TITLE
Cleanup unnecessary intermediate conversions

### PR DESCRIPTION
**Pull request by a1ien**
Use bytes for data manipulation. It's faster and not need convert to string and back to bytes for struct.unpack

### CODE REVIEW

**Comment by Magalex2x14** [comment]
Hurrah! Finally, a man appeared who drew attention to this :)
Yes, I know, but there were many other tasks, and my hands did not reach. Thank you!

I’ll take a look later.

**Comment by Magalex2x14** [comment]
This continues from the very beginning, from the time when we received strings at the input.

**Comment by Ernst79** [comment]
Look good to me. I’m very limited in time this week, so I don’t have time to do a real live test unfortunately. But I suppose you have checked it on a running HA, @Magalex2x14 . I suggest that you merge it. Thank for your help @a1ien , much appreciated!

**Comment by Magalex2x14** [comment]
There are no errors during execution, but the data does not come. Need debugging.
@a1ien does this code work for you?

**Comment by a1ien** [comment]
Yes. But also I test it with additional patch for NUC.

**Comment by Magalex2x14** [comment]
@a1ien I have discovered a problem. The code works, but for some reason HA created new entities with this code... It remains to understand why.

image

After restoring the old code, the correct entities are updated.

**Comment by Magalex2x14** [comment]
Perhaps some kind of confusion with the types?

**Comment by Magalex2x14** [comment]
Guessed a peek into the .storage/core.entity_registry :)
image

**Pull request merged**
